apiVersion: v1
kind: Service
metadata:
  name: swish-service
spec:
  type: NodePort
  selector:
    app: swish
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.containerPort }}
      nodePort: 30080
