apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}
    team: {{ .Values.team | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      team: {{ .Values.team | quote }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        team: {{ .Values.team | quote }}
    spec:
      nodeSelector:
        team: {{ .Values.team | quote }}

      tolerations:
        - key: "team"
          operator: "Equal"
          value: {{ .Values.team | quote }}
          effect: "NoSchedule"

      containers:
        - name: swish
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sleep", "infinity"]
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.resources.cpu | quote }}
              memory: {{ .Values.resources.memory | quote }}
