apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}-autoscaler
spec:
  scaleTargetRef:
    name: {{ .Release.Name }}-deployment
  minReplicaCount: 0
  maxReplicaCount: 1
  pollingInterval: 15          # szybsze sprawdzanie
  cooldownPeriod: 60           # zeskaluje po 60s od idle
  initialCooldownPeriod: 30
  triggers:
    - type: prometheus
      metadata:
        serverAddress: "http://prometheus-operated.monitoring:9090"
        metricName: {{ .Release.Name }}-cpu-idle
        query: |
          avg_over_time(container_cpu_usage_seconds_total{
            container!="",
            namespace="{{ .Release.Namespace }}",
            pod=~"{{ .Release.Name }}.*"
          }[30s]) or vector(0)
        threshold: "{{ .Values.autoscaling.threshold }}"
