apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}-autoscaler
spec:
  scaleTargetRef:
    name: {{ .Release.Name }}-service
  minReplicaCount: 0
  maxReplicaCount: {{ .Values.autoscaling.maxReplicaCount }}
  pollingInterval: {{ .Values.autoscaling.pollingInterval }}
  cooldownPeriod: {{ .Values.autoscaling.cooldownPeriod }}
  triggers:
    - type: prometheus
      metadata:
        serverAddress: "http://prometheus-operated.monitoring:9090"
        metricName: {{ .Release.Name }}-cpu-idle
        query: |
          avg(
            avg_over_time(container_cpu_usage_seconds_total{
              namespace="{{ .Release.Namespace }}",
              pod=~"{{ .Release.Name }}.*"
            }[{{ .Values.autoscaling.queryRange }}])
          ) * 100
        threshold: "{{ .Values.autoscaling.threshold }}"
