apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
    team: {{ .Values.team | quote }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.containerPort }}
