name: Build and Test on PR

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy with Helm'
        required: false
        default: false
        type: boolean


jobs:
  permissions:
    id-token: write
    contents: read

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker tag from short SHA
        run: echo "TAG_NAME=sha-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: ./swish-base-docker
          load: true
          tags: vallher/swish-base-docker:${{ env.TAG_NAME }}

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: vallher/swish-base-docker:${{ env.TAG_NAME }}
          format: table
          severity: CRITICAL
          exit-code: 1
          output: trivy-report.json

      - name: Upload Trivy scan report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report-${{ env.TAG_NAME }}
          path: trivy-report.json
          retention-days: 5

      - name: Push image
        run: docker push vallher/swish-base-docker:${{ env.TAG_NAME }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::350152846698:role/github-actions-eks-deploy
          aws-region: us-east-1
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Deploy app with Helm
        if: github.ref == 'refs/heads/main' || github.event.inputs.deploy == 'true'
        run: |
          aws eks update-kubeconfig --region us-east-1 --name swish-play
