name: Build, test and deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy with Helm'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.set_tag.outputs.IMAGE_TAG }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker tag from short SHA
        id: set_tag
        run: |
          IMAGE_TAG="sha-$(echo $GITHUB_SHA | cut -c1-7)"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: ./general/docker/py2py3r
          load: true
          tags: vallher/py2py3r:${{ env.IMAGE_TAG }}

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: vallher/py2py3r:${{ env.IMAGE_TAG }}
          format: table
          severity: CRITICAL
          exit-code: 1
          output: trivy-report.json

      - name: Upload Trivy scan report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report-${{ env.IMAGE_TAG }}
          path: trivy-report.json
          retention-days: 5

      - name: Push image
        run: docker push vallher/py2py3r:${{ env.IMAGE_TAG }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event.inputs.deploy == 'true'
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::350152846698:role/github-actions-eks-deploy
          aws-region: us-east-1

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Helm template
        run: |
          helm template swish-app ./general/helm/base-app

      - name: Deploy app with Helm
        run: |
          aws eks update-kubeconfig --region us-east-1 --name swish-play-general
          helm upgrade --install swish-app ./general/helm/base-app \
            --namespace swish \
            --create-namespace \
            --set image.repository=vallher/py2py3r \
            --set image.tag=${{ needs.build.outputs.IMAGE_TAG }}
